default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.8
        args: ["--line-length=88"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace # Remove trailing spaces
        args: [--markdown-linebreak-ext=md]
        exclude: ^\.github/.*$
      - id: end-of-file-fixer # Add newline to end of files

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies: ["flake8-blind-except", "flake8-tidy-imports"]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        args: []
        additional_dependencies: [tokenize-rt==3.2.0]
